---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gobudjmb/public_html/
    - /bin/cp -R .output/public/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .env $DEPLOYPATH/ 2>/dev/null || true